lem/views/common.py
import flask
from flask import Blueprint, current_app as app, redirect, session, url_for
from flask_login import login_user, logout_user, login_required
from flask_principal import AnonymousIdentity, Identity, identity_changed, PermissionDenied

from lem.business import auth_user
from lem.forms import LoginForm

common = Blueprint('common', __name__)


@common.route('/', methods=['GET'])
@login_required
def home():
    return flask.render_template('home.html')


@common.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = auth_user(form.data['email'], form.data['password'])
        if user:
            login_user(user)

            # Tell Flask-Principal the identity changed
            identity_changed.send(app._get_current_object(),
                                  identity=Identity(user.id))

            next_action = flask.request.args.get('next')
            return flask.redirect(next_action or flask.url_for('common.home'))
        else:
            flask.flash('Credenciais inválidas', 'error')

    return flask.render_template('login/login.html', form=form)


@common.route('/logout', methods=['GET'])
@login_required
def logout():
    logout_user()

    # Remove session keys set by Flask-Principal
    for key in ('identity.name', 'identity.auth_type'):
        session.pop(key, None)
    # Tell Flask-Principal the user is anonymous
    identity_changed.send(app._get_current_object(),
                          identity=AnonymousIdentity())

    return flask.redirect(flask.url_for('common.login'))


@common.route('/forbidden', methods=['GET'])
def forbidden():
    return flask.render_template('site/forbidden.html'), 403


def internal_server_error(exception):
    if isinstance(exception, PermissionDenied):
        return redirect(url_for('common.forbidden'))
    return flask.render_template('site/internal_server_error.html'), 500


def not_found(exception):
    return flask.render_template('site/not_found.html'), 404

lem/templates/site/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% if site_title %}{{site_title}} | {% endif %}Luizalabs Employee Manager</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" />
    {% block css %}
        {% include "site/css.html" %}
    {% endblock %}

</head>
<body class="hold-transition skin-blue sidebar-mini">
<!-- Site wrapper -->
<div class="wrapper">

  <header class="main-header">
    <!-- Logo -->
    <a href="{{ url_for('common.home') }}" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b>LEM</b></span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><b>Employee Manager</b></span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    {% block header %}
        {% include "site/header.html" %}
    {% endblock %}
  </header>

  <!-- =============================================== -->

  <!-- Left side column. contains the sidebar -->
    {% block nav %}
        {% include "site/nav.html" %}
    {% endblock %}

  <!-- =============================================== -->

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    {% block pageTitle %}
      <section class="content-header">
          <h1>{% block pageTitleContent %}{% endblock pageTitleContent %}</h1>
      </section>
    {% endblock pageTitle %}
    <section class="content">
        {% block content %}
        {% endblock content %}
    </section>
  </div>

  {% block footer %}
      {% include "site/footer.html" %}
  {% endblock %}
</div>
<!-- ./wrapper -->

{# script is shared site JavaScript #}
{% block body_end_script %}
    {% if not js_in_head %}
      {% include "site/javascript.html" %}
    {% endif %}
{% endblock body_end_script %}
</body>
</html>

lem/templates/site/css.html
    <!-- Bootstrap 3.3.7 -->
    <link href="{{ url_for('static', filename='assets/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet" type="text/css" />
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link href="{{ url_for('static', filename='assets/dist/css/AdminLTE.min.css') }}" rel="stylesheet" type="text/css" />
    <!-- AdminLTE Skins. Choose a skin from the css/skins
    folder instead of downloading all of them to reduce the load. -->
    <link href="{{ url_for('static', filename='assets/dist/css/skins/_all-skins.min.css') }}" rel="stylesheet" type="text/css" />

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->

    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

lem/templates/site/footer.html
<footer class="main-footer">
<div class="pull-right hidden-xs">
  <b>Versão</b> 1.0.0
</div>
    2017 &copy; Luizalabs Employee Manager
</footer>

lem/templates/site/forbidden.html
{% extends "site/base.html" %}

{% block content %}
<div class="error-page">
    <br>
    <h2 class="headline text-yellow">403</h2>
    <div class="error-content">
        <br>
      <h3><i class="fa fa-warning text-yellow"></i> Oops! Acesso negado.</h3>
      <p>
          {% if current_user.is_authenticated %}
            <a href="{{ url_for('common.home') }}" class="btn btn-block btn-success"> Ir para o início </a>
          {% else %}
            <a href="{{ url_for('common.login') }}" class="btn btn-block btn-success"> Login </a>
          {% endif %}
      </p>
    </div>
</div>
{% endblock content %}

lem/templates/site/header.html
<nav class="navbar navbar-static-top">
  <!-- Sidebar toggle button-->
  <a href="{{ url_for('common.home') }}" class="sidebar-toggle" data-toggle="offcanvas" role="button">
    <span class="sr-only">Toggle navigation</span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </a>

  <div class="navbar-custom-menu">
    <ul class="nav navbar-nav">
      <!-- User Account: style can be found in dropdown.less -->
      <li class="dropdown user user-menu">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          <span>{{ current_user.email }}</span>
        </a>
        <ul class="dropdown-menu">
          <li class="user-footer">
            <div class="pull-right">
              <a href="{{ url_for('common.logout') }}" class="btn btn-default btn-flat">Sair</a>
            </div>
          </li>
        </ul>
      </li>
    </ul>
  </div>
</nav>

lem/templates/site/internal_server_error.html
{% extends "site/base.html" %}

{% block content %}
<div class="error-page">
    <br>
    <h2 class="headline text-red">500</h2>
    <div class="error-content">
        <br>
      <h3><i class="fa fa-warning text-red"></i> Oops! Ocorreu um erro no servidor.</h3>
      <p>
          {% if current_user.is_authenticated %}
            <a href="{{ url_for('common.home') }}" class="btn btn-block btn-success"> Ir para o início </a>
          {% else %}
            <a href="{{ url_for('common.login') }}" class="btn btn-block btn-success"> Login </a>
          {% endif %}
      </p>
    </div>
</div>
{% endblock content %}

lem/templates/site/javascript.html
<!-- jQuery 2.2.3 -->
<script src="{{ url_for('static', filename='assets/plugins/jQuery/jquery-2.2.3.min.js') }}" type="text/javascript"></script>
<!-- Bootstrap 3.3.7 -->
<script src="{{ url_for('static', filename='assets/bootstrap/js/bootstrap.min.js') }}" type="text/javascript"></script>
<!-- AdminLTE App -->
<script src="{{ url_for('static', filename='assets/dist/js/app.min.js') }}" type="text/javascript"></script>
<!-- AdminLTE for demo purposes -->
<script src="{{ url_for('static', filename='assets/dist/js/demo.js') }}" type="text/javascript"></script>

lem/templates/site/messages.html
{% set visuals = {'error': 'danger'} %}
{% with messages = get_flashed_messages(with_categories=true) %}
    {% for category, msg in messages %}
        {% if category %}
            <div {% if msg.msg_id %}id="{{ msg.msg_id }}"{% endif %} class="alert alert-{{ visuals.get(category, category) }}">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                {{ msg }}
            </div>
        {% else %}
            <div {% if msg.msg_id %}id="{{ msg.msg_id }}"{% endif %} class="alert alert-danger">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                {{ msg }}
            </div>
        {% endif %}
    {% endfor %}
{% endwith %}

lem/templates/site/nav.html
<aside class="main-sidebar">
<!-- sidebar: style can be found in sidebar.less -->
<section class="sidebar">
  <!-- sidebar menu: : style can be found in sidebar.less -->
  <ul class="sidebar-menu">
      <li class="header">MENU</li>
      <li {% if request.endpoint in ['employee.index', 'employee.create', 'employee.edit'] %} class="active" {% endif %}>
          <a href="{{ url_for('employee.index') }}"><i class="fa fa-users"></i> <span>Empregados</span></a>
      </li>
  </ul>
</section>
<!-- /.sidebar -->
</aside>

lem/templates/site/not_found.html
{% extends "site/base.html" %}

{% block content %}
<div class="error-page">
    <br>
    <h2 class="headline text-yellow">404</h2>
    <div class="error-content">
        <br>
      <h3><i class="fa fa-warning text-yellow"></i> Oops! Recurso não encontrado.</h3>
      <p>
        A url ou recurso não foi encontrado ou não existe.
      </p>
    </div>
</div>
{% endblock content %}