lem/models/employee.py
import datetime

from lem import db


def dump_datetime(value):
    """Deserialize datetime object into string form for JSON processing."""
    if value is None:
        return None
    return value.strftime("%Y-%m-%d %H:%M:%S")


class Employee(db.Model):
    __tablename__ = 'employee'

    DATA_GROUPS = 'groups'

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    name = db.Column(db.String(255), nullable=False)
    email = db.Column(db.String(255), nullable=False, index=True, unique=True)
    department = db.Column(db.String(255), nullable=False)
    created_dt = db.Column(db.DateTime, default=datetime.datetime.utcnow, nullable=False)
    updated_dt = db.Column(db.DateTime, onupdate=datetime.datetime.utcnow, nullable=True)

    @property
    def serialize(self):
        """Return object data in easily serializeable format"""
        return {
            'id': self.id,
            'name': self.name,
            'email': self.email,
            'department': self.department,
            'created_dt': dump_datetime(self.created_dt),
            'updated_dt': dump_datetime(self.updated_dt)
        }

    @property
    def serialize_many2many(self):
        """
        Return object's relations in easily serializeable format.
        NB! Calls many2many's serialize property.
        """
        return [item.serialize for item in self.many2many]

lem/views/api.py
from flask import Blueprint, jsonify, request
from sqlalchemy.exc import IntegrityError
from werkzeug.exceptions import Conflict

from lem import db
from lem.models import Employee
from utils.decorators import requires_json, requires_fields_validation

api = Blueprint('api', __name__, url_prefix='/api')


@api.route('/', methods=['GET'])
def index():
    return jsonify({"service": "Luizalabs Employee Manager",
                    "version": "1.0"})


@api.route('/employee', methods=['GET'])
def get_employee_list():
    employees = Employee.query.all()
    return jsonify(employees=[i.serialize for i in employees])


@requires_fields_validation
@requires_json
@api.route('/employee', methods=['POST'])
def post_employee():
    r = request.json
    employee = Employee()
    employee.name = r['name']
    employee.email = r['email']
    employee.department = r['department']

    db.session.add(employee)

    try:
        db.session.commit()
    except IntegrityError as e:
        db.session.rollback()
        raise Conflict("Integrity error: {0}".format(str(e)))

    return jsonify(employee.serialize)


@api.route('/employee/<employee_id>', methods=['PUT'])
def put_employee(employee_id):
    r = request.json
    employee = Employee.query.filter_by(id=employee_id).first_or_404()
    employee.name = r['name']
    employee.email = r['email']
    employee.department = r['department']

    db.session.add(employee)

    try:
        db.session.commit()
    except IntegrityError as e:
        db.session.rollback()
        raise Conflict("Integrity error: {0}".format(str(e)))

    return jsonify(employee.serialize)


@api.route('/employee/<employee_id>', methods=['DELETE'])
def delete_employee(employee_id):
    employee = Employee.query.filter_by(id=employee_id).first_or_404()
    db.session.delete(employee)
    db.session.commit()
    return ''

lem/views/employee.py
import json

import flask
from flask import Blueprint, request, redirect, url_for
from flask_login import login_required

from lem import db
from lem.forms import EmployeeForm
from lem.models import Employee
from utils.decorators import requires_json

employee = Blueprint('employee', __name__, url_prefix='/employee')


@employee.route('/', methods=['GET'])
@login_required
def index():
    return flask.render_template('employee/list.html')


@employee.route('/create', methods=['GET', 'POST'])
@login_required
def create():
    employeeForm = EmployeeForm()
    if request.method == 'POST':
        if employeeForm.validate_on_submit():
            employee = Employee()
            employee.name = employeeForm.data['name']
            employee.email = employeeForm.data['email']
            employee.department = employeeForm.data['department']
            db.session.add(employee)
            try:
                db.session.commit()
                flask.flash('Empregado cadastrado com sucesso', 'success')
                return redirect(url_for('employee.index'))
            except Exception as e:
                db.session.rollback()
                flask.flash('Erro ao criar empregado', 'error')

    return flask.render_template('employee/create.html', form=employeeForm)


@employee.route('/edit', methods=['GET', 'POST'])
@employee.route('/edit/<employee_id>',  methods=['GET'])
@login_required
def edit(employee_id=None):
    employeeForm = EmployeeForm()
    if not employee_id:
        employee_id = request.args.get('id')
    employee = Employee.query.filter_by(id=employee_id).first_or_404()
    if request.method == 'POST':
        if employeeForm.validate_on_submit():
            employee.name = employeeForm.data['name']
            employee.email = employeeForm.data['email']
            employee.department = employeeForm.data['department']
            db.session.add(employee)
            try:
                db.session.commit()
                flask.flash('Empregado atualizado com sucesso', 'success')
                return redirect(url_for('employee.index'))
            except Exception as e:
                db.session.rollback()
                flask.flash('Erro ao atualizar empregado', 'error')

    employeeForm.name.data = employee.name
    employeeForm.email.data = employee.email
    employeeForm.department.data = employee.department
    return flask.render_template('employee/edit.html', employee=employee, form=employeeForm)


@requires_json
@employee.route('/remove', methods=['POST'])
@login_required
def remove():
    data = json.loads(request.data.decode('utf-8'))
    employee = Employee.query.filter_by(id=data['employee_id']).first_or_404()
    db.session.delete(employee)
    try:
        db.session.commit()
    except Exception as e:
        db.session.rollback()
        return '', 400

    return ''

lem/templates/employee/create.html
{% extends "site/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block pageTitleContent %}
    Criar novo Empregado
{% endblock pageTitleContent %}

{% block css %}
    {{ super() }}
    <!-- DataTables -->
    <link href="{{ url_for('static', filename='assets/plugins/datatables/dataTables.bootstrap.css') }}" rel="stylesheet" type="text/css" />
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-xs-12">
        <div id="system-alerts">
            {% include "site/messages.html" %}
        </div>
          <div class="box">
            <div class="box-body">
                <form method="POST" role="form" action="{{ url_for('employee.create') }}">
                    <div class="modal-body">
                      {{ form.hidden_tag() }}
                      {{ wtf.form_errors(form, hiddens="only") }}
                      <div class="form-group has-feedback">
                          {{ wtf.form_field(form.name) }}
                      </div>
                      <div class="form-group has-feedback">
                          {{ wtf.form_field(form.email) }}
                      </div>
                      <div class="form-group has-feedback">
                          {{ wtf.form_field(form.department) }}
                      </div>
                    </div>
                    <div class="modal-footer">
                        <a href="{{ url_for('employee.index') }}" class="btn btn-danger" data-dismiss="modal">Voltar</a>
                        <button type="submit" class="btn btn-primary">Salvar</button>
                    </div>
                </form>
            </div>
          </div>
        </div>
    </div>
</div>
{% endblock content %}


{% block body_end_script %}
    {{ super() }}
    <!-- DataTables -->
    <script src="{{ url_for('static', filename='assets/plugins/datatables/jquery.dataTables.min.js') }}" type="text/javascript"></script>
    <script src="{{ url_for('static', filename='assets/plugins/datatables/dataTables.bootstrap.min.js') }}" type="text/javascript"></script>

    <script src="{{ url_for('static', filename='js/employee.js') }}" type="text/javascript"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            Employee.init({
                fetchUrl: '{{ url_for('api.get_employee_list') }}',
            });
        });
    </script>
{% endblock body_end_script %}

lem/templates/employee/edit.html
{% extends "site/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block pageTitleContent %}
    Editar {{employee.name}}
{% endblock pageTitleContent %}

{% block css %}
    {{ super() }}
    <!-- DataTables -->
    <link href="{{ url_for('static', filename='assets/plugins/datatables/dataTables.bootstrap.css') }}" rel="stylesheet" type="text/css" />
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-xs-12">
        <div id="system-alerts">
            {% include "site/messages.html" %}
        </div>
          <div class="box">
            <div class="box-body">
                 <form method="POST" role="form" action="{{ url_for('employee.edit', id=employee.id) }}">
                  <div class="modal-body">
                      {{ form.hidden_tag() }}
                      {{ wtf.form_errors(form, hiddens="only") }}
                      <div class="form-group has-feedback">
                          {{ wtf.form_field(form.name) }}
                      </div>
                      <div class="form-group has-feedback">
                          {{ wtf.form_field(form.email) }}
                      </div>
                      <div class="form-group has-feedback">
                          {{ wtf.form_field(form.department) }}
                      </div>
                  </div>
                  <div class="modal-footer">
                    <a href="{{ url_for('employee.index') }}" class="btn btn-danger" data-dismiss="modal">Voltar</a>
                    <button type="submit" class="btn btn-primary">Salvar</button>
                  </div>
                </form>
            </div>
          </div>
        </div>
    </div>
</div>
{% endblock content %}


{% block body_end_script %}
    {{ super() }}
    <!-- DataTables -->
    <script src="{{ url_for('static', filename='assets/plugins/datatables/jquery.dataTables.min.js') }}" type="text/javascript"></script>
    <script src="{{ url_for('static', filename='assets/plugins/datatables/dataTables.bootstrap.min.js') }}" type="text/javascript"></script>

    <script src="{{ url_for('static', filename='js/employee.js') }}" type="text/javascript"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            Employee.init({
                fetchUrl: '{{ url_for('api.get_employee_list') }}',
            });
        });
    </script>
{% endblock body_end_script %}

lem/templates/employee/list.html
{% extends "site/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block pageTitleContent %}
    Empregados
{% endblock pageTitleContent %}

{% block css %}
    {{ super() }}
    <!-- DataTables -->
    <link href="{{ url_for('static', filename='assets/plugins/datatables/dataTables.bootstrap.css') }}" rel="stylesheet" type="text/css" />
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-xs-12">
        <div id="system-alerts">
            {% include "site/messages.html" %}
        </div>
          <div class="box">
            <!-- /.box-header -->
              <div class="box-header">
                  <div class="col-md-offset-9 col-md-3">
                      <a href="{{ url_for('employee.create') }}"><button type="button" class="btn btn-block btn-primary ">Criar novo empregado</button></a>
                  </div>
              </div>
            <div class="box-body">
                <table class="table table-bordered table-striped dataTable" id="datatable_employees">
                    <thead>
                        <tr role="row">
                            <th rowspan="1" colspan="1">#ID</th>
                            <th rowspan="1" colspan="1">Nome</th>
                            <th rowspan="1" colspan="1">Email</th>
                            <th rowspan="1" colspan="1">Departamento</th>
                            <th rowspan="1" colspan="1">Ações</th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                    <tfoot>
                    <tr>
                        <th rowspan="1" colspan="1">#ID</th>
                        <th rowspan="1" colspan="1">Nome</th>
                        <th rowspan="1" colspan="1">Email</th>
                        <th rowspan="1" colspan="1">Departamento</th>
                        <th rowspan="1" colspan="1">Ações</th>
                    </tr>
                    </tfoot>
              </table>
            </div>
            <!-- /.box-body -->
          </div>
        </div>
    </div>
</div>
{% endblock content %}


{% block body_end_script %}
    {{ super() }}
    <!-- DataTables -->
    <script src="{{ url_for('static', filename='assets/plugins/datatables/jquery.dataTables.min.js') }}" type="text/javascript"></script>
    <script src="{{ url_for('static', filename='assets/plugins/datatables/dataTables.bootstrap.min.js') }}" type="text/javascript"></script>

    <script src="{{ url_for('static', filename='js/employee.js') }}" type="text/javascript"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            Employee.init({
                fetchUrl: '{{ url_for('api.get_employee_list') }}',
                editUrl:  '{{ url_for('employee.edit') }}',
                removeUrl: '{{ url_for('employee.remove') }}',
            });
        });
    </script>
{% endblock body_end_script %}